[package]
name = "hh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
clap = { version = "3.1.12", features = ["cargo"] }
hashbrown = "0.12" 
memchr = "2.4"
